# -*- coding: utf-8 -*-
"""dickTest2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjdik6tJfOmc8l3xuellrsj-7vqCVaWd
"""

!pip install konlpy
import sys
import os
import pickle
# 정확한 경로를 확인하고 추가
module_path = '/content/drive/MyDrive/chatbot/utils'
if module_path not in sys.path:
    sys.path.append(module_path)

# 경로에 process.py 파일이 있는지 확인
print("파일 존재 여부:", os.path.exists(os.path.join(module_path, 'process.py')))


# 모듈 불러오기
from process import Preprocess


# 단어 사전 불러오기
f = open("/content/drive/MyDrive/chatbot/train_tool/dict/chatbot_dict.bin", "rb")
word_index = pickle.load(f)
f.close()

sent = "컴공짜응"

# 전처리 객체 생성
p = Preprocess(userdic='/content/drive/MyDrive/chatbot/utils/user_dic.tsv')

# 형태소분석기 실행
pos = p.pos(sent)

# 품사 태그 없이 키워드 출력
keywords = p.get_keywords(pos, without_tag=True)
for word in keywords:
    try:
        print(word, word_index[word])
    except KeyError:
        # 해당 단어가 사전에 없는 경우, OOV 처리
        print(word, word_index['OOV'])

from google.colab import drive
drive.mount('/content/drive')